/**
 * API iSendPro
 * [1] Liste des fonctionnalités : - envoi de SMS à un ou plusieurs destinataires, - lookup HLR, - récupération des récapitulatifs de campagne, - gestion des répertoires, - ajout en liste noire. - comptage du nombre de caractères des SMS  [2] Pour utiliser cette API vous devez: - Créer un compte iSendPro sur https://isendpro.com/ - Créditer votre compte      - Remarque: obtention d'un crédit de test possible sous conditions - Noter votre clé de compte (keyid)   - Elle vous sera indispensable à l'utilisation de l'API   - Vous pouvez la trouver dans le rubrique mon \"compte\", sous-rubrique \"mon API\" - Configurer le contrôle IP   - Le contrôle IP est configurable dans le rubrique mon \"compte\", sous-rubrique \"mon API\"   - Il s'agit d'un système de liste blanche, vous devez entrer les IP utilisées pour appeler l'API   - Vous pouvez également désactiver totalement le contrôle IP 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@isendpro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * REPERTOIREcreaterequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T09:49:05.172Z")
public class REPERTOIREcreaterequest   {
  @SerializedName("keyid")
  private String keyid = null;

  /**
   * Action à réaliser doit valoir \"create\" ici.
   */
  public enum RepertoireEditEnum {
    @SerializedName("create")
    CREATE("create");

    private String value;

    RepertoireEditEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("repertoireEdit")
  private RepertoireEditEnum repertoireEdit = RepertoireEditEnum.CREATE;

  @SerializedName("repertoireNom")
  private String repertoireNom = null;

  public REPERTOIREcreaterequest keyid(String keyid) {
    this.keyid = keyid;
    return this;
  }

   /**
   * Clé API
   * @return keyid
  **/
  @ApiModelProperty(example = "null", required = true, value = "Clé API")
  public String getKeyid() {
    return keyid;
  }

  public void setKeyid(String keyid) {
    this.keyid = keyid;
  }

  public REPERTOIREcreaterequest repertoireEdit(RepertoireEditEnum repertoireEdit) {
    this.repertoireEdit = repertoireEdit;
    return this;
  }

   /**
   * Action à réaliser doit valoir \"create\" ici.
   * @return repertoireEdit
  **/
  @ApiModelProperty(example = "null", required = true, value = "Action à réaliser doit valoir \"create\" ici.")
  public RepertoireEditEnum getRepertoireEdit() {
    return repertoireEdit;
  }

  public void setRepertoireEdit(RepertoireEditEnum repertoireEdit) {
    this.repertoireEdit = repertoireEdit;
  }

  public REPERTOIREcreaterequest repertoireNom(String repertoireNom) {
    this.repertoireNom = repertoireNom;
    return this;
  }

   /**
   * Nom du répertoire (libellé) à créer
   * @return repertoireNom
  **/
  @ApiModelProperty(example = "null", required = true, value = "Nom du répertoire (libellé) à créer")
  public String getRepertoireNom() {
    return repertoireNom;
  }

  public void setRepertoireNom(String repertoireNom) {
    this.repertoireNom = repertoireNom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    REPERTOIREcreaterequest rEPERTOIREcreaterequest = (REPERTOIREcreaterequest) o;
    return Objects.equals(this.keyid, rEPERTOIREcreaterequest.keyid) &&
        Objects.equals(this.repertoireEdit, rEPERTOIREcreaterequest.repertoireEdit) &&
        Objects.equals(this.repertoireNom, rEPERTOIREcreaterequest.repertoireNom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyid, repertoireEdit, repertoireNom);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class REPERTOIREcreaterequest {\n");
    
    sb.append("    keyid: ").append(toIndentedString(keyid)).append("\n");
    sb.append("    repertoireEdit: ").append(toIndentedString(repertoireEdit)).append("\n");
    sb.append("    repertoireNom: ").append(toIndentedString(repertoireNom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

